package com.bhuppi.qbittorrentremote.domain.model

data class Torrent(
    val addedOn: Long = 0,
    val amountLeft: Long = 0,
    val autoTmm: Boolean = false,
    val availability: Double = 0.0,
    val category: String = "",
    val completed: Long = 0,
    val completionOn: Long = 0,
    val contentPath: String = "",
    val dlLimit: Long = 0,
    val dlspeed: Int = 0,
    val downloaded: Long = 0,
    val downloadedSession: Long = 0,
    val eta: Int = 0,
    val flPiecePrio: Boolean = false,
    val forceStart: Boolean = false,
    val hash: String = "",
    val lastActivity: Long = 0,
    val magnetUri: String = "",
    val maxRatio: Double = 0.0,
    val maxSeedingTime: Long = 0,
    val name: String = "",
    val numComplete: Int = 0,
    val numIncomplete: Int = 0,
    val numLeechs: Int = 0,
    val numSeeds: Int = 0,
    val priority: Int = 0,
    val progress: Double = 0.0,
    val ratio: Double = 0.0,
    val savePath: String = "",
    val seedingTime: Long = 0,
    val seenComplete: Long = 0,
    val seqDl: Boolean = false,
    val size: Long = 0,
    val state: String = "",
    val superSeeding: Boolean = false,
    val tags: String = "",
    val timeActive: Long = 0,
    val totalSize: Long = 0,
    val tracker: String = "",
    val upLimit: Long = 0,
    val uploaded: Long = 0,
    val uploadedSession: Long = 0,
    val upspeed: Int = 0
)
