package com.bhuppi.qbittorrentremote.domain.model

data class TorrentProperties(
    val savePath: String = "",
    val creationDate: Long = 0,
    val pieceSize: Long = 0,
    val comment: String = "",
    val totalWasted: Long = 0,
    val totalUploaded: Long = 0,
    val totalUploadedSession: Long = 0,
    val totalDownloaded: Long = 0,
    val totalDownloadedSession: Long = 0,
    val upLimit: Long = 0,
    val dlLimit: Long = 0,
    val timeElapsed: Long = 0,
    val seedingTime: Long = 0,
    val nbConnections: Int = 0,
    val nbConnectionsLimit: Int = 0,
    val shareRatio: Double = 0.0,
    val additionDate: Long = 0,
    val completionDate: Long = 0,
    val createdBy: String = "",
    val dlSpeedAvg: Long = 0,
    val dlSpeed: Long = 0,
    val eta: Long = 0,
    val lastSeen: Long = 0,
    val peers: Int = 0,
    val peersTotal: Int = 0,
    val piecesHave: Int = 0,
    val piecesNum: Int = 0,
    val reannounce: Long = 0,
    val seeds: Int = 0,
    val seedsTotal: Int = 0,
    val totalSize: Long = 0,
    val upSpeedAvg: Long = 0,
    val upSpeed: Long = 0
)
